Adds support for RDS storage autoscaling.
tablexi/terraform_modules pull request #213
Opened 2021-10-25 11:57 UTC by dougbradbury

Adds the parameter for 'max_allocated_storage' to enable AWS's new
autoscaling feature.
https://aws.amazon.com/about-aws/whats-new/2019/06/rds-storage-auto-scaling/
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#storage-autoscaling

2021-10-25 17:20 UTC, ahorner requested changes
Thanks for contributing! I'm in favor of supporting this feature, but we'll want to make sure we still properly support the module for cases where storage autoscaling isn't desired.

2021-10-25 17:20 UTC, ahorner commented on aws/rds/variables.tf
> +  type        = number
This needs a default value, or it will cause an issue for any uses of the module that don't specify this variable. We should probably support a fallback value that avoids enabling this setting (`0` seems like a good candidate) so we can flag off of it in the module.

2021-10-26 12:00 UTC, dougbradbury commented on aws/rds/variables.tf
> +  type        = number
I added a default of null. That seems to leave the autoscaling feature off.

2022-02-08 20:51 UTC, phoolish commented
Oops, I didn't see this PR before we worked on #215.

2022-02-08 20:51 UTC, closed without merging

2022-02-08 21:17 UTC, dougbradbury commented
So sad.  I'm glad you added support for it though.  I will switch off my fork.  Looks like you chose the same naming convention?

2022-02-08 21:32 UTC, phoolish commented
Yup, same naming convention `max_allocated_storage`